#-------------------------------
# Site Settings

title: Yurafiq
logo: # You can add own logo. For example '/images/logo.png'.
description: Yurafiq – Accompagnement personnaliser 

menu__settings:
  menu__items:
    - title: 'Accuiel'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Services'
      url: '/blog/'
    - title: 'A Propos'
      submenu:
      - url: '/about'
        title: 'About'
      - url: '/elements'
        title: 'Certifications'

# Call to action button
cta__button__text: Prenez Contact

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Yurafiq
  title: Yurafiq - En cours de dev ...
  bio: Des Architectes Cloud & DevOps basé en France depuis plusieurs années, mettent en œuvre des architectures cloud, conçoivent des plateformes web et mobile. sont également amené à automatiser et industrialiser des infrastructures cloud. 
       Accompagnent des entrepreneurs dans la réalisation et concrétisation de leurs différents projets. Accompagnement les mosquée de manière bénévole dans la réalisation de leurs projets informatiques et bien d'autres services que vous pouvez consulter sur notre site internet en fonction de vos besoins.  
  image: '/images/Yurafiq.png'
  avatar: '/images/Yurafiq.png'
  button__text: Nos réalisations


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: NOS DERNIÈRES <span class="text-span">REALISATIONS</span> # Add a 'text-span' class to highlight text.
  projects__description: Nos meilleures réalisations web, cloud et DevOps construites entièrement avec passion, simplicité et créativité !


#-------------------------------
# Testimonials Section

testimonial__title: LES <span class="text-span">TÉMOIGNAGES</span>

testimonial-items:
  - name: "Karim EL KAIAL"
    image: "/images/karim.jfif"
    designation : "Architecte Unix - Accenture"
    content : "Yurafiq une équipe experts Gentille, sociable, à l'écoute, assidu. Comme points fort, ils sont motivé, autonome dans leurs travail, efficace, polyvalent dans le domaine et surtout curieux"

  - name: "Thomas PELTIER"
    image: "/images/thomas.jfif"
    designation : "Ingénieur Infra-IT - Equinix"
    content : "Eugène expert Yurafiq est agréable à vivre, à l'écoute pour ses collègues avec beaucoup d'empathie, travailleur, motivé, déterminé et très ambitieux. Il est une personne attachant, comme amélioration à faire, il faut qu'il s'affirme un peu plus auprès des autres collaborateurs."

  - name: "Elhadj Oumar DOUMBOUYA"
    image: "/images/oumar.jfif"
    designation : "Ingénieur DevOps - Accenture"
    content : "Les experts Yurafiq sont rigoureuses dans le travail, calme et sympathique, Forte capacité d'analyse, grande vitesse de compréhension, sérénité à toutes épreuves, Esprit d'équipe, Curiosité, Envie d'apprendre et de progresser. Avec Eugène les limites sont sans fin."

  - name: "Cheick Traore"
    image: "/images/cheick.png"
    designation : "Architecte Cloud - Devoteam"
    content : "J'ai collaboré pendant 1 an avec Eugene aujourd'hui expert de Yurafiq. durant cette année travaillé avec Eugene a été vraiment un plus pour moi de par son expérience et sa prise de hauteur sur les sujets complexes de plus Eugene est quelqu’un qui m'as permis de monter rapidement en compétences pour passer des certifications d'architecte Azure."

  - name: "Gaëtan ONAHETA"
    image: "/images/gaetan.jfif"
    designation : "Architecte Unix - Indépendant"
    content : "Eugène expert de Yurafiq sait écouter et comprendre (c'est rare aujourd'hui), très agile, s'adapte et répond au besoin ou changements demandés. Très organisé dans son travail, il est transparent le long de son projet. Selon moi, son atout majeur, c'est sa capacité d'analyse, elle lui permet de voir large afin de poser les bonnes questions et de répondre de manière ciblée, efficace et pertinente avec des solutions techniques adaptées, claires et précises."

#-------------------------------
# Blog Section

blog__settings:
  blog__title: Nos<span class="text-span">Services</span> # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: contact@yurafiq.fr # Add your email for contact form
  contact__title: <span class="text-span">Prenez</span> Contact # Add a title to your form
  contact__description: Formulaire de contact. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Inscrivez-vous</span> à la newsletter # Add your title
  mailchimp__text: " 'Obtenez de inspiration et des trucs cool sur le coaching personnel ! ' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Abonnez-vous # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: UA-239784083-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/eug%C3%A8ne-rodolphe-mazamda-tangueu-82612b151/"}
- {icon: "ion-logo-github", link: "https://github.com/eugenemazamda"}
- {icon: "fa fa-gitlab", link: "https://gitlab.com/rodolphemazamda"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCmERV6qF_w3QHtzhT2gx5Yg"}